### ISSUE TITLE
Can't get sensors

### ISSUE THREAD

**Issue by dawiduniec** [bieniu/ha-airly#4]
https://airapi.airly.eu/v2/installations/nearest?lat=54.3&lng=18.624&maxDistanceKM=3&maxResults=1

This returns somethins, but in hass I'm getting:

Can't retrieve data: no Airly sensors in this area
11:08 custom_components/airly/sensor.py (ERROR)

**Comment by dawiduniec** [comment]
Why are you not using "create_measurements_session_nearest" ?

**Comment by bieniu** [comment]
Because official Airly map use "interpolation/point" mode.
